# Generated by Django 5.0.6 on 2024-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="Remote", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(default="empty"),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(default="500", max_length=100),
        ),
    ]
