# Generated by Django 5.0.6 on 2024-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_job_is_active_job_location_job_requirements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="total_applicants",
            field=models.IntegerField(default=0),
        ),
    ]
